name: McTeams
version: 1.0
main: fr.mcteams.McTeamsPlugin
depend: [WorldGuard]
commands:
  setspawn:
    description: Définit le spawn du serveur
  spawn:
    description: Se téléporter au spawn
  go:
    description: Gestion des homes
  team:
    description: Gestion de la team
    aliases: [t]
  buy:
    description: Acheter un item
  sell:
    description: Vendre un item
  buyview:
    description: Voir le marché
  deposit:
    description: Convertir l'or en monnaie virtuelle
  balance:
    description: Voir son solde
  setrank:
    description: Set rank du joueur
